//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FunctionModels : DbContext
    {
        public FunctionModels()
            : base("name=FunctionModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoxInfo> BoxInfoes { get; set; }
        public virtual DbSet<FaouriteTheatreList> FaouriteTheatreLists { get; set; }
        public virtual DbSet<FavouriteFilmList> FavouriteFilmLists { get; set; }
        public virtual DbSet<PurchasingRecord> PurchasingRecords { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
    }
}
