//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string user_id { get; set; }
        public decimal film_id { get; set; }
        public decimal rate { get; set; }
        public string comment { get; set; }
        public System.DateTime date { get; set; }
    }
}
